In [1]:
import gym
import or_gym.envs
from or_gym.envs.classic_or.knapsack import KnapsackEnv
import numpy as np

In [2]:
envs = gym.make('Knapsack-v0')

In [21]:
class BoundedKnapsackEnv(KnapsackEnv):
    
    def __init__(self):
        self.item_limits_init = np.array([2, 1, 3, 4, 5, 6])
        self.item_limits = self.item_limits_init.copy()
        super().__init__()
        
    def step(self, item):
        # Check item limit
        if self.item_limits[item] > 0:
            # Check that item will fit
            if self.item_weights[item] + self.current_weight <= self.max_weight:
                self.current_weight += self.item_weights[item]
                reward = self.item_values[item]
                if self.current_weight == self.max_weight:
                    done = True
                else:
                    done = False
            else:
                # End if over weight
                reward = 0
                done = True
        else:
            # End if item is unavailable
            reward = 0
            done = True
            
        self._update_state()
        return self.state, reward, done, {}
        
    def _update_state(self, item=None):
        if item is not None:
            self.item_limits[item] -= 1
            
        self.state = (self.item_weights,
                      self.item_values,
                      self.item_limits,
                      self.current_weight)
        
    def sample_action(self):
        return np.random.choice(
            self.item_numbers[np.where(self.item_limits!=0)])
    
    def reset(self):
        self.current_weight = 0
        self.item_limits = self.item_limits_init.copy()
        self._update_state()
        return self.state

In [22]:
env = BoundedKnapsackEnv()

In [23]:
done = False
actions = []
count = 0
while done == False:
    action = env.sample_action()
    s, r, done, _ = env.step(action)
    count += 1

In [25]:
env.reset()

(array([ 1,  2,  3,  6, 10, 18]),
 array([  0,   1,   3,  14,  20, 100]),
 array([2, 1, 3, 4, 5, 6]),
 0)

2