In [1]:
import or_gym
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
env = or_gym.make('InvManagement-v0')

In [3]:
env.state

array([100., 200., 400.])

In [4]:
env.action_space.sample()

array([99.02318 , 55.225838, 18.610294], dtype=float32)

In [26]:
s, r, done, info = env.step(np.array([20, 20, 20]))

In [21]:
s

array([ 99., 199., 399.])

In [24]:
env.reset()

array([100., 200., 400.])

In [27]:
env.D

array([21.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [30]:
for i in range(1):
    rewards = []
    env.reset()
    done = False
    while done == False:
        action = env.sample_action()
        s, r, done, _ = env.step(action)
        rewards.append(r)
        if done:
            print('{}\n{}'.format(i, env.D))

0
[28. 19. 14. 13. 17. 19. 21. 21. 18. 16. 19. 30. 18. 17. 13. 15. 23. 20.
 19. 16. 24. 21. 23. 25. 27. 17. 19. 20. 23. 18.]


In [31]:
rewards

[-0.06532988880332233,
 0.5511385526697721,
 0.43272712272939007,
 0.11016821839440796,
 -0.12065091600542738,
 -0.5178899278105419,
 -0.5881249431783062,
 -0.7750160687125532,
 -0.9220568438764394,
 -0.9267867827794425,
 -1.0368280861783703,
 -0.9588681815414347,
 -1.0705733930666532,
 -1.2644880873110846,
 -1.2660439635212577,
 -1.3076243727994008,
 -1.3825281484131786,
 -1.5028867531014762,
 -1.6134168610347988,
 -1.6179823124927475,
 -1.625076703068963,
 -1.7207434530911518,
 -1.7016109222483307,
 -1.7051196878049013,
 -1.667614506010566,
 -1.7400640416386233,
 -1.7990178396450769,
 -1.8702645261714472,
 -1.9044328373456652,
 -1.9758852720274318]

In [10]:
env.unit_cost

array([1.5 , 1.  , 0.75, 0.5 ])

In [11]:
env.demand_cost

array([0.1  , 0.075, 0.05 , 0.025])

In [12]:
env.holding_cost

array([0.15, 0.1 , 0.05, 0.  ])

In [13]:
env.discount

0.97

In [22]:
env.discount**env.period*np.sum(env.unit_price*np.ones(env.unit_price.shape) \
                                - (env.unit_cost*np.ones(env.unit_cost.shape) \
                                  + env.demand_cost*0 + env.holding_cost * 0))

0.6015106028147362

In [23]:
env.P

array([-16.1       ,   9.38475   ,   8.7268475 , -25.4635767 ,
       -26.16040254, -46.6292576 , -35.35966161, -23.4315025 ,
       -17.10519882, -26.17095419, -32.35448357, -50.82216469,
       -30.45967965, -49.92178441, -54.33229919, -47.88962118,
       -45.97688596, -55.14370036, -38.43375896, -25.05938879,
       -24.7426426 , -39.02037092, -39.88359278, -39.07172247,
       -46.10773443, -53.73711421, -43.91500174, -55.18568842,
       -39.50829552, -51.33510591])

In [29]:
env.demand_dist.pmf(env.D[env.period-1], **env.dist_param)

0.06456106691469761

In [ ]:
1/30 * np.sum(prob)