In [1]:
import numpy as np
import or_gym
from or_gym.algos.knapsack.heuristics import *
from or_gym.algos.knapsack.math_prog import *
from or_gym.algos.math_prog_utils import *
import matplotlib.pyplot as plt
%matplotlib inline

# Instantiate Unbounded Knapsack Model

Baseline model generates weights as random integers from $[1, 20]$ and values from $[0, 30]$.

In [39]:
env = or_gym.make('Knapsack-v0')

#### IP Model

In [40]:
model = build_ukp_ip_model(env)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

IP Objective: 5600.00
x_i = 200_188


In [41]:
heur_actions, heur_rewards = ukp_heuristic(env)
x_h = np.unique(heur_actions)
i_h = len(heur_actions)
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
print("x_i = {}_{}".format(i_h, x_h[0]))

Heuristic Objective: 5600.00
x_i = 200_188


In [69]:
# Try new settings for weights and values
env.reset()
env.item_values = np.random.rand(env.N)
env.item_weights = np.random.rand(env.N)
env.max_weight = 20

model = build_ukp_ip_model(env)
model, results = solve_math_program(model)
print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i))
     for i, x in enumerate(model.x) if model.x[x].value != 0]
print("\t")
# Heuristic
heur_actions, heur_rewards = ukp_heuristic(env)
count = np.bincount(heur_actions)
action_count = count[count!=0]
actions = np.where(count!=0)
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
_ = [print("x_i = {:.0f}_{}".format(x, i)) 
     for x, i in zip(action_count, actions[0])]

print(env.current_weight)

IP Objective: 1279.16
x_i = 1_44
x_i = 1_68
x_i = 2032_71
	
Heuristic Objective: 1279.09
x_i = 1_44
x_i = 2033_71
19.995972355098996


In [66]:
env.current_weight

19.999482624596983

In [57]:
heur_actions.append(1)

In [52]:
np.where(np.bincount(heur_actions)!=0)

(array([  1, 101]),)

In [54]:
count = np.bincount(heur_actions)

In [55]:
count[count!=0]

array([   1, 4804])

In [60]:
count = np.bincount(heur_actions)
action_count = count[count!=0]
actions = np.where(count!=0)[0]
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
_ = [print("x_i = {:.0f}_{}".format(x, i)) 
     for x, i in zip(actions, action_count)]

Heuristic Objective: 4424.49
x_i = 1_1
x_i = 101_4804


In [59]:
actions

(array([  1, 101]),)