In [1]:
import numpy as np
import or_gym
from or_gym.algos.knapsack.heuristics import *
from or_gym.algos.knapsack.math_prog import *
from or_gym.algos.math_prog_utils import *
import matplotlib.pyplot as plt
import pandas as pd
import time
from pyomo.environ import *
%matplotlib inline

# Instantiate Unbounded Knapsack Model

Baseline model generates weights as random integers from $[1, 20]$ and values from $[0, 30]$.

In [5]:
env_config = {'mask': True}
env0 = or_gym.make('Knapsack-v0', env_config=env_config) # Unbounded
env1 = or_gym.make('Knapsack-v1', env_config=env_config) # Binary
env2 = or_gym.make('Knapsack-v2') # Bounded
env3 = or_gym.make('Knapsack-v3') # Online

In [6]:
env1.step(27)

({'action_mask': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1]),
  'avail_actions': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 

#### IP Model

In [5]:
model = build_ukp_ip_model(env0)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

IP Objective: 10400.00
x_i = 200_2


In [6]:
model = build_bin_ip_model(env1)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

IP Objective: 1488.00
x_i = 1_8
x_i = 1_11
x_i = 1_17
x_i = 1_24
x_i = 1_34
x_i = 1_40
x_i = 1_41
x_i = 1_45
x_i = 1_51
x_i = 1_55
x_i = 1_67
x_i = 1_69
x_i = 1_75
x_i = 1_76
x_i = 1_85
x_i = 1_96
x_i = 1_107
x_i = 1_119
x_i = 1_134
x_i = 1_159
x_i = 1_165
x_i = 1_166
x_i = 1_178


In [7]:
model = build_bkp_ip_model(env2)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

IP Objective: 2696.00
x_i = 2_1
x_i = 4_2
x_i = 9_11
x_i = 2_34
x_i = 2_39
x_i = 4_56
x_i = 6_76
x_i = 1_77
x_i = 1_103
x_i = 5_122
x_i = 2_187


In [8]:
model = build_okp_ip_model(env3)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

IP Objective: 591.00
x_i = 1_0
x_i = 1_1
x_i = 1_2
x_i = 1_3
x_i = 1_6
x_i = 1_7
x_i = 1_8
x_i = 1_9
x_i = 1_10
x_i = 1_12
x_i = 1_14
x_i = 1_15
x_i = 1_17
x_i = 1_20
x_i = 1_22
x_i = 1_24
x_i = 1_26
x_i = 1_28
x_i = 1_31
x_i = 1_32
x_i = 1_34
x_i = 1_35
x_i = 1_36
x_i = 1_40
x_i = 1_41
x_i = 1_42
x_i = 1_43
x_i = 1_44
x_i = 1_45
x_i = 1_48
x_i = 1_49


In [30]:
env0.item_weights = np.random.randint(1, 100, 200)

In [32]:
env0.item_values

array([66,  2,  1, 42, 90, 69, 76, 86, 92, 73, 62,  5, 63, 30, 59, 41, 86,
       35, 82, 83, 66, 44, 44, 21, 70, 35, 22, 36, 32, 13, 42, 14, 44, 19,
        3, 91, 74, 72, 94, 10, 99, 32, 67, 91, 60, 46, 45, 31, 90, 92, 81,
       45, 28, 24, 72, 90, 11, 95, 70, 97, 46, 29, 67, 75, 12, 12, 33, 41,
       88, 77, 74, 37, 74, 57, 50, 28,  4,  2, 53, 58, 29, 61, 33, 77, 57,
       21, 77, 94, 35, 18, 96, 63, 59, 41, 94, 54, 90, 65, 49, 93, 14, 14,
       28,  5, 87, 29, 51, 73, 44, 15, 96, 63, 10, 89, 75, 90, 36, 67, 40,
       51, 22, 44,  8, 44, 61, 17, 46, 73, 56, 27, 23, 72, 20, 31, 41, 11,
       92, 17, 88, 35, 68, 87, 62, 31,  2, 69, 75, 86, 43, 59, 22, 11, 95,
       76, 22,  6, 14, 58, 25, 31, 25, 81, 68, 40, 38, 58, 30, 20, 44, 65,
       84, 35, 26, 57, 14, 74, 39, 57, 87, 40, 76, 30, 14, 17, 71, 67, 34,
        3, 34, 55, 39, 35, 86, 73, 85, 91, 17, 59, 79, 54])

In [33]:
def build_ukp_ip_model(env):
    env.item_weights 
    # Initialize model
    m = ConcreteModel()

    # Sets, parameters, and variables
    m.W = env.max_weight
    m.i = Set(initialize=env.item_numbers)
    m.w = Param(m.i, 
        initialize={i: j for i, j in zip(env.item_numbers, env.item_weights)})
    m.v = Param(m.i, 
        initialize={i: j for i, j in zip(env.item_numbers, env.item_values)})
    m.x = Var(m.i, within=NonNegativeReals)

    @m.Constraint()
    def weight_constraint(m):
        return sum(m.w[i] * m.x[i] for i in m.i) - m.W <= 0

    m.obj = Objective(expr=(
        sum([m.v[i] * m.x[i] for i in m.i])),
        sense=maximize)
    
    return m

In [34]:
model = build_ukp_ip_model(env0)
model, results = solve_math_program(model)
results

{'Problem': [{'Name': 'unknown', 'Lower bound': 17200.0, 'Upper bound': 17200.0, 'Number of objectives': 1, 'Number of constraints': 2, 'Number of variables': 201, 'Number of nonzeros': 201, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': 0, 'Number of created subproblems': 0}}, 'Error rc': 0, 'Time': 0.013911008834838867}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [35]:
[model.x[i].value for i in model.x]

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 200.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0

In [10]:
model = build_bkp_ip_model(env1)
model, results = solve_math_program(model)
results

{'Problem': [{'Name': 'unknown', 'Lower bound': 1528.0, 'Upper bound': 1528.0, 'Number of objectives': 1, 'Number of constraints': 202, 'Number of variables': 201, 'Number of nonzeros': 398, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '39', 'Number of created subproblems': '39'}}, 'Error rc': 0, 'Time': 0.018499374389648438}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [12]:
model = build_bin_ip_model(env0)
model, results = solve_math_program(model)
results

{'Problem': [{'Name': 'unknown', 'Lower bound': 1839.0, 'Upper bound': 1839.0, 'Number of objectives': 1, 'Number of constraints': 2, 'Number of variables': 201, 'Number of nonzeros': 200, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '5', 'Number of created subproblems': '5'}}, 'Error rc': 0, 'Time': 0.012799978256225586}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [21]:
env.item_weights.shape

(200,)

In [24]:
env.max_weight

200

In [6]:
model = build_ukp_ip_model(env)
model, results = solve_math_program(model)

print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i)) 
     for i, x in enumerate(model.x) if model.x[x].value != 0]

ERROR: evaluating object as numeric value: x[0]
        (object: <class 'pyomo.core.base.var._GeneralVarData'>)
    No value for uninitialized NumericValue object x[0]


ValueError: No value for uninitialized NumericValue object x[0]

In [4]:
heur_actions, heur_rewards = ukp_heuristic(env)
x_h = np.unique(heur_actions)
i_h = len(heur_actions)
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
print("x_i = {}_{}".format(i_h, x_h[0]))

Heuristic Objective: 5600.00
x_i = 200_188


In [5]:
# Get data from Beasley
url = 'http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/mdmkp_ct9.txt'
data = pd.read_csv(url)

In [6]:
data

15
0                                               500 30 
1     462 691 941 638 63 1000 39 84 520 425 982 642 ...
2     531 845 506 64 211 464 387 76 451 913 651 503 ...
3     729 702 263 408 480 453 392 737 75 557 818 858...
4     170 367 460 355 250 401 323 643 375 26 882 368...
...                                                 ...
1030  720 567 853 253 578 595 465 711 558 459 787 34...
1031  366 646 444 603 514 169 521 345 458 370 672 57...
1032  357 718 657 173 284 681 -426 494 315 282 82 12...
1033  -83 417 620 -59 -143 -67 -100 481 223 -115 374...
1034  283 -225 -9 -256 514 -213 502 -106 -97 -251 30...

[1035 rows x 1 columns]

In [9]:
env.item_numbers

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [43]:
weights, values, total_rewards = [], [], []
env = or_gym.make('Knapsack-v1')
count = 0
samples = 0
t0 = time.time()
while len(weights) < 5000:
    env.item_values = np.random.randint(0, 100, env.N)
    env.item_weights = np.random.randint(1, 100, env.N)
    env.item_limits_init = np.ones(env.N)
    env.reset()
    # Solve IP
    model = build_ukp_ip_model(env)
    model, results = solve_math_program(model)
    # Solve with Heuristic
    heur_actions, heur_rewards = bkp_heuristic(env)
    
    tot_h_rewards = sum(heur_rewards)
    samples += 1
    if tot_h_rewards != model.obj.expr():
        weights.append(env.item_weights.copy())
        values.append(env.item_values.copy())
        total_rewards.append((model.obj.expr(), tot_h_rewards))
        count += 1
        if count % 100 == 0 and count > 0:
            print("{} parameters found in {:.1f} seconds.".format(count, time.time() - t0))

100 parameters found in 4.3 seconds.
200 parameters found in 8.9 seconds.
300 parameters found in 13.8 seconds.
400 parameters found in 18.6 seconds.
500 parameters found in 23.6 seconds.
600 parameters found in 28.2 seconds.
700 parameters found in 32.6 seconds.
800 parameters found in 36.9 seconds.
900 parameters found in 41.5 seconds.
1000 parameters found in 45.7 seconds.
1100 parameters found in 50.8 seconds.
1200 parameters found in 55.4 seconds.
1300 parameters found in 60.0 seconds.
1400 parameters found in 65.0 seconds.
1500 parameters found in 69.3 seconds.
1600 parameters found in 74.2 seconds.
1700 parameters found in 79.5 seconds.
1800 parameters found in 85.3 seconds.
1900 parameters found in 90.2 seconds.
2000 parameters found in 95.1 seconds.
2100 parameters found in 99.8 seconds.
2200 parameters found in 104.7 seconds.
2300 parameters found in 110.6 seconds.
2400 parameters found in 115.1 seconds.
2500 parameters found in 120.2 seconds.
2600 parameters found in 125.4 s

In [44]:
r = np.vstack(total_rewards).T
assert sum(r[0]>r[1]) == count
m = (r[0] - r[1]).argmax()
print("Max diff = {:.2f}%, sample_n = {}".format((1 - r[1, m]/r[0, m])*100, m))
print("Non-optimal rate: {:.2f}%".format(count/samples*100))

Max diff = 3.59%, sample_n = 4166
Non-optimal rate: 64.33%


In [46]:
values[m]

array([18, 64, 79, 30, 79, 33, 69, 87, 17, 56, 95,  5, 88, 39, 18, 80, 59,
        9, 71, 80, 85, 44, 78, 88,  2, 40, 96, 99, 18, 99, 56, 64, 49, 90,
       18, 52, 44, 57, 60, 33,  3, 22, 14, 74, 11,  2, 23,  8, 90, 17, 44,
        0, 29, 80, 50,  9, 28, 19, 15, 32, 82, 98, 91, 41, 73, 35, 69,  3,
       80,  0, 35, 97, 26, 66, 47,  0, 21, 27, 66, 91, 54, 73, 79, 86, 63,
        3, 35, 60, 68, 33, 84, 40, 84, 46, 39, 15, 21, 98, 93, 92, 46, 49,
       26, 90, 44, 89, 34, 13, 52, 56, 24, 18, 77, 46, 98, 67, 66, 74, 40,
        5, 44, 49, 61, 54, 89, 87, 75, 58, 51, 22, 41, 54, 50, 93,  1, 17,
       93, 21, 52, 99, 94, 57, 90, 49, 58, 41, 16, 54, 60, 70, 71, 34, 37,
       43, 77, 89, 20, 40, 82, 17, 26, 92, 72, 44, 37,  2, 14, 45, 46, 31,
       18, 73, 28, 62, 33, 40, 18, 72, 13, 26, 44, 69, 47, 71, 65, 54, 71,
       92, 29, 96, 71, 72, 51, 82, 95, 87, 73, 79, 37, 51])

In [51]:
# BKP
weights, values, limits, total_rewards = [], [], [], []
env = or_gym.make('Knapsack-v1')
count = 0
samples = 0
t0 = time.time()
while len(weights) < 5000:
    env.item_values = np.random.randint(0, 100, env.N)
    env.item_weights = np.random.randint(1, 100, env.N)
    env.item_limits_init = np.random.randint(0, 10, env.N)
    env.reset()
    # Solve IP
    model = build_bkp_ip_model(env)
    model, results = solve_math_program(model)
    # Solve with Heuristic
    heur_actions, heur_rewards = bkp_heuristic(env)
    
    tot_h_rewards = sum(heur_rewards)
    samples += 1
    if tot_h_rewards != model.obj.expr():
        weights.append(env.item_weights.copy())
        values.append(env.item_values.copy())
        limits.append(env.item_limits_init.copy())
        total_rewards.append((model.obj.expr(), tot_h_rewards))
        count += 1
        if count % 100 == 0 and count > 0:
            print("{} parameters found in {:.1f} seconds.".format(count, time.time() - t0))
            
r = np.vstack(total_rewards).T
assert sum(r[0]>r[1]) == count
m = (r[0] - r[1]).argmax()
print("Max diff = {:.2f}%, sample_n = {}".format((1 - r[1, m]/r[0, m])*100, m))
print("Non-optimal rate: {:.2f}%".format(count/samples*100))

100 parameters found in 6.9 seconds.
200 parameters found in 13.5 seconds.
300 parameters found in 20.4 seconds.
400 parameters found in 27.4 seconds.
500 parameters found in 34.5 seconds.
600 parameters found in 42.2 seconds.
700 parameters found in 49.0 seconds.
800 parameters found in 55.3 seconds.
900 parameters found in 62.5 seconds.
1000 parameters found in 70.9 seconds.
1100 parameters found in 78.6 seconds.
1200 parameters found in 86.3 seconds.
1300 parameters found in 92.8 seconds.
1400 parameters found in 100.1 seconds.
1500 parameters found in 106.9 seconds.
1600 parameters found in 114.5 seconds.
1700 parameters found in 121.8 seconds.
1800 parameters found in 128.9 seconds.
1900 parameters found in 136.0 seconds.
2000 parameters found in 144.5 seconds.
2100 parameters found in 151.2 seconds.
2200 parameters found in 159.1 seconds.
2300 parameters found in 166.6 seconds.
2400 parameters found in 174.0 seconds.
2500 parameters found in 181.4 seconds.
2600 parameters found i

In [52]:
weights[m]

array([66,  2,  1, 42, 90, 69, 76, 86, 92, 73, 62,  5, 63, 30, 59, 41, 86,
       35, 82, 83, 66, 44, 44, 21, 70, 35, 22, 36, 32, 13, 42, 14, 44, 19,
        3, 91, 74, 72, 94, 10, 99, 32, 67, 91, 60, 46, 45, 31, 90, 92, 81,
       45, 28, 24, 72, 90, 11, 95, 70, 97, 46, 29, 67, 75, 12, 12, 33, 41,
       88, 77, 74, 37, 74, 57, 50, 28,  4,  2, 53, 58, 29, 61, 33, 77, 57,
       21, 77, 94, 35, 18, 96, 63, 59, 41, 94, 54, 90, 65, 49, 93, 14, 14,
       28,  5, 87, 29, 51, 73, 44, 15, 96, 63, 10, 89, 75, 90, 36, 67, 40,
       51, 22, 44,  8, 44, 61, 17, 46, 73, 56, 27, 23, 72, 20, 31, 41, 11,
       92, 17, 88, 35, 68, 87, 62, 31,  2, 69, 75, 86, 43, 59, 22, 11, 95,
       76, 22,  6, 14, 58, 25, 31, 25, 81, 68, 40, 38, 58, 30, 20, 44, 65,
       84, 35, 26, 57, 14, 74, 39, 57, 87, 40, 76, 30, 14, 17, 71, 67, 34,
        3, 34, 55, 39, 35, 86, 73, 85, 91, 17, 59, 79, 54])

In [53]:
values[m]

array([56, 26, 52, 29, 29, 36, 38, 80, 86,  5, 91, 56, 50, 86, 13, 22, 24,
       69, 16, 77, 81, 87, 16, 48, 94, 62, 16, 51, 10, 56, 72, 25, 49,  5,
       82, 40, 54, 66, 24, 88, 38, 99, 32, 89, 53, 81, 26, 17, 10,  2, 72,
       57, 60, 73, 92, 35, 98, 12, 14, 96,  6, 22, 60, 15, 83, 90, 27, 33,
       22, 37,  5,  1, 32, 75, 86, 29, 86, 29, 81, 62, 67,  4, 49, 10, 56,
       67, 44,  2, 48, 41, 85, 25, 61, 82,  5, 16, 98, 70, 90, 65, 57, 61,
       66, 64, 24, 64, 12, 88, 88, 70, 14, 54, 60,  1, 18, 42, 12,  9, 27,
       33, 54, 17, 93, 99, 52, 16, 33, 78, 47, 78, 92, 63, 57, 86,  8, 65,
       33, 44, 43, 49, 10, 60, 74,  3, 30, 85, 33, 46,  0,  8,  1, 88, 96,
       52, 11,  9, 37, 54, 61, 78, 43, 86, 24, 23, 38, 84, 86, 97, 50, 27,
       55, 51, 41,  4, 37, 16, 67, 30, 64, 13, 51, 33,  3, 60, 23, 47, 66,
       63,  2, 14,  4, 90, 23, 82, 42, 72, 73, 47, 62, 90])

In [54]:
limits[m]

array([2, 2, 4, 1, 2, 9, 6, 1, 5, 0, 3, 9, 0, 7, 7, 2, 5, 4, 6, 0, 6, 5,
       5, 5, 4, 4, 9, 9, 7, 3, 9, 2, 4, 6, 2, 2, 9, 1, 8, 4, 1, 3, 6, 8,
       2, 9, 0, 3, 4, 5, 9, 4, 4, 3, 3, 4, 8, 7, 1, 1, 3, 9, 2, 0, 7, 0,
       8, 2, 1, 5, 6, 1, 8, 2, 4, 9, 6, 1, 9, 8, 0, 3, 4, 2, 1, 7, 8, 1,
       2, 6, 5, 7, 4, 4, 5, 8, 7, 9, 0, 6, 4, 6, 6, 1, 1, 0, 8, 5, 7, 2,
       5, 8, 0, 9, 5, 0, 3, 9, 3, 9, 6, 5, 5, 1, 8, 4, 8, 4, 8, 4, 9, 0,
       7, 3, 4, 8, 2, 8, 5, 4, 5, 6, 3, 3, 0, 4, 6, 6, 1, 3, 4, 1, 7, 5,
       2, 5, 2, 0, 6, 4, 2, 5, 8, 9, 6, 9, 5, 1, 3, 8, 1, 4, 6, 8, 4, 5,
       4, 5, 6, 6, 4, 1, 3, 9, 7, 0, 1, 2, 5, 7, 7, 8, 7, 0, 6, 4, 4, 5,
       5, 0])

In [ ]:
# UKP
weights, values, total_rewards = [], [], []
env = or_gym.make('Knapsack-v1')
count = 0
samples = 0
t0 = time.time()
while len(weights) < 5000:
    env.item_values = np.random.randint(0, 100, env.N)
    env.item_weights = np.random.randint(1, 100, env.N)
    env.item_limits_init = np.random.randint(0, 10, env.N)
    env.reset()
    # Solve IP
    model = build_bkp_ip_model(env)
    model, results = solve_math_program(model)
    # Solve with Heuristic
    heur_actions, heur_rewards = bkp_heuristic(env)
    
    tot_h_rewards = sum(heur_rewards)
    samples += 1
    if tot_h_rewards != model.obj.expr():
        weights.append(env.item_weights.copy())
        values.append(env.item_values.copy())
        total_rewards.append((model.obj.expr(), tot_h_rewards))
        count += 1
        if count % 100 == 0 and count > 0:
            print("{} parameters found in {:.1f} seconds.".format(count, time.time() - t0))
            
r = np.vstack(total_rewards).T
assert sum(r[0]>r[1]) == count
m = (r[0] - r[1]).argmax()
print("Max diff = {:.2f}%, sample_n = {}".format((1 - r[1, m]/r[0, m])*100, m))
print("Non-optimal rate: {:.2f}%".format(count/samples*100))

In [6]:
# Try new settings for weights and values
env = or_gym.make('Knapsack-v1')
env.item_values = np.random.randint(0, 100, env.N)
env.item_weights = np.random.randint(1, 100, env.N)
# env.item_values = np.array([15, 100, 90, 60, 40, 15, 10, 1])
# env.item_weights = np.array([2, 20, 20, 30, 40, 30, 60, 10])
# env.N = len(env.item_values)
# env.item_numbers = np.arange(env.N)
# env.max_weight = 102
env.item_limits_init = np.ones(env.N)
env.reset()

model = build_ukp_ip_model(env)
model, results = solve_math_program(model)
print("IP Objective: {:.2f}".format(model.obj.expr()))
_ = [print("x_i = {:.0f}_{}".format(model.x[x].value, i))
     for i, x in enumerate(model.x) if model.x[x].value != 0]
print("\t")
# Heuristic
heur_actions, heur_rewards = bkp_heuristic(env)
count = np.bincount(heur_actions)
action_count = count[count!=0]
actions = np.where(count!=0)
print("Heuristic Objective: {:.2f}".format(sum(heur_rewards)))
_ = [print("x_i = {:.0f}_{}".format(x, i))
     for x, i in zip(action_count, actions[0])]

print(env.current_weight)

IP Objective: 1700.00
x_i = 1_1
x_i = 1_9
x_i = 1_13
x_i = 1_17
x_i = 1_25
x_i = 1_32
x_i = 1_45
x_i = 1_54
x_i = 1_57
x_i = 1_79
x_i = 1_83
x_i = 1_88
x_i = 1_120
x_i = 1_127
x_i = 1_129
x_i = 1_146
x_i = 1_161
x_i = 1_165
x_i = 1_171
x_i = 1_177
x_i = 1_178
x_i = 1_190
x_i = 1_195
x_i = 1_197
	
Heuristic Objective: 1696.00
x_i = 1_1
x_i = 1_13
x_i = 1_17
x_i = 1_25
x_i = 1_32
x_i = 1_45
x_i = 1_54
x_i = 1_57
x_i = 1_79
x_i = 1_88
x_i = 1_120
x_i = 1_127
x_i = 1_129
x_i = 1_146
x_i = 1_150
x_i = 1_161
x_i = 1_163
x_i = 1_165
x_i = 1_171
x_i = 1_177
x_i = 1_178
x_i = 1_190
x_i = 1_195
x_i = 1_197
199


In [27]:
env.item_limits

array([0., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
heur_actions

[0, 0]

In [12]:
env.reset()

{'action_mask': array([1, 1, 1, 1, 1, 1, 1, 1]),
 'avail_actions': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'state': array([[  2.,  20.,  20.,  30.,  40.,  30.,  60.,  10., 102.],
        [ 15., 100.,  90.,  60.,  40.,  15.,  10.,   1.,   0.],
        [  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   0.]])}

In [22]:
vw_ratio = env.item_values / env.item_weights
vw_order = env.item_numbers[np.argsort(vw_ratio)[::-1]]
actions, rewards = [], []
done = False
while not done:
    max_item = vw_order[0]
    cont_flag = False
    if env.item_limits[max_item] == 0:
        # Remove item from list
        vw_order = vw_order[1:].copy()
        cont_flag = True
    elif env.item_weights[max_item] > (env.max_weight - env.current_weight):
        # Remove item from list
        vw_order = vw_order[1:].copy()
        cont_flag = True
    if len(vw_order) == 0:
        # End episode
        break
    if cont_flag:
        # Item doesn't fit or exist, start over
        continue
    state, reward, done, _ = env.step(max_item)
    actions.append(max_item)
    rewards.append(reward)

In [24]:
sum(rewards)

265

In [20]:
env.item_values

array([ 15, 100,  90,  60,  40,  15,  10,   1])

In [21]:
env.item_weights

array([ 2, 20, 20, 30, 40, 30, 60, 10])